// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webthucphamsach.Data;

#nullable disable

namespace webthucphamsach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529060046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webthucphamsach.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rau xanh hữu cơ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trái cây sạch"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trứng & Sữa tươi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đặc sản vùng miền"
                        });
                });

            modelBuilder.Entity("webthucphamsach.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Cải bó xôi tươi giòn, giàu chất sắt và vitamin, trồng theo tiêu chuẩn hữu cơ, không thuốc hóa học.",
                            ImageUrl = "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80",
                            Name = "Rau cải bó xôi hữu cơ Đà Lạt",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Táo Fuji giòn ngọt, mọng nước, nhập khẩu chính ngạch từ trang trại đạt chuẩn hữu cơ thế giới.",
                            ImageUrl = "https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=600&auto=format&fit=crop&q=80",
                            Name = "Táo đỏ Fuji hữu cơ cao cấp",
                            Price = 89000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Củ cà rốt tươi ngon, ngọt đậm, thích hợp dùng làm nước ép hoặc chế biến món ăn bổ dưỡng mỗi ngày.",
                            ImageUrl = "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&auto=format&fit=crop&q=80",
                            Name = "Cà rốt ngọt Đà Lạt VietGAP",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Dâu tây căng mọng, vị chua ngọt hài hòa, được thu hoạch trực tiếp tại vườn công nghệ cao vào sáng sớm.",
                            ImageUrl = "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&auto=format&fit=crop&q=80",
                            Name = "Dâu tây đỏ New Zealand trồng Đà Lạt",
                            Price = 120000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Trứng từ đàn gà ta thả vườn được nuôi dưỡng bằng thảo mộc tự nhiên, hàm lượng dinh dưỡng cao vượt trội.",
                            ImageUrl = "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80",
                            Name = "Trứng gà ta thảo mộc tự nhiên",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Mật ong rừng tự nhiên nguyên chất 100%, mùi thơm đặc trưng, vị ngọt thanh tốt cho hệ tiêu hóa.",
                            ImageUrl = "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80",
                            Name = "Mật ong rừng tràm U Minh nguyên chất",
                            Price = 180000m
                        });
                });

            modelBuilder.Entity("webthucphamsach.Models.Product", b =>
                {
                    b.HasOne("webthucphamsach.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("webthucphamsach.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
