// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebThucPhamSach.Data;

#nullable disable

namespace WebThucPhamSach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527085703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebThucPhamSach.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rau củ hữu cơ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trái cây tươi sạch"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thịt & Hải sản sạch"
                        });
                });

            modelBuilder.Entity("WebThucPhamSach.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Cải bó xôi trồng theo tiêu chuẩn hữu cơ VietGAP, không thuốc trừ sâu, thu hoạch buổi sáng đảm bảo độ tươi ngon.",
                            ImageUrl = "cai-bo-xoi.jpg",
                            Name = "Cải bó xôi hữu cơ",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Cà chua bi Đà Lạt đạt chứng nhận GlobalGAP, vị ngọt tự nhiên, màu đỏ đẹp, phù hợp salad và nấu ăn.",
                            ImageUrl = "ca-chua-bi.jpg",
                            Name = "Cà chua bi đà lạt",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Xoài cát Hòa Lộc chính hiệu Tiền Giang, thịt vàng dày, ngọt thanh, không xơ, đạt tiêu chuẩn xuất khẩu.",
                            ImageUrl = "xoai-cat.jpg",
                            Name = "Xoài cát Hòa Lộc",
                            Price = 85000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Bơ sáp 034 từ Đắk Lắk, béo ngậy tự nhiên, giàu vitamin E và chất béo tốt, chín đều không đắng.",
                            ImageUrl = "bo-sap.jpg",
                            Name = "Bơ sáp 034 Đắk Lắk",
                            Price = 65000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Thịt lợn nuôi hoàn toàn bằng thức ăn hữu cơ, không kháng sinh, không chất tăng trưởng, đảm bảo an toàn thực phẩm.",
                            ImageUrl = "thit-lon-organic.jpg",
                            Name = "Thịt lợn hữu cơ Organic",
                            Price = 185000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
